"""add_payment_tables

Revision ID: 9e5fd851b910
Revises: e2f3a4b5c6d7
Create Date: 2026-04-03 09:34:47.872535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e5fd851b910'
down_revision: Union[str, None] = 'e2f3a4b5c6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_log', 'resource',
               existing_type=sa.VARCHAR(length=100),
               comment='操作资源(user/role/enterprise/bid_project/credential/...)',
               existing_comment='操作资源(user/role/mine/drawing/project/...)',
               existing_nullable=False)
    op.alter_column('bid_chapter', 'edit_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='用户编辑占比(0~1)，由反馈飞轮写入',
               existing_nullable=True)
    op.alter_column('bid_chapter', 'ai_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               comment='AI原创占比(0~1)，高风险字段替换后降低',
               existing_server_default=sa.text('0.0'))
    op.alter_column('bid_chapter', 'source_tags',
               existing_type=sa.TEXT(),
               nullable=False,
               comment='内容来源标签，逗号分隔: ai_generated,company_db,template,credential',
               existing_server_default=sa.text("''::text"))
    op.alter_column('bid_competitor', 'tenant_id',
               existing_type=sa.INTEGER(),
               comment='租户ID',
               existing_nullable=False)
    op.alter_column('bid_competitor', 'competitor_name',
               existing_type=sa.VARCHAR(length=200),
               comment='竞争企业名称',
               existing_nullable=False)
    op.alter_column('bid_competitor', 'competitor_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='对手报价（万元）',
               existing_nullable=True)
    op.alter_column('bid_competitor', 'competitor_result',
               existing_type=sa.VARCHAR(length=20),
               comment='对手结果: won/lost/disqualified',
               existing_nullable=True)
    op.alter_column('bid_competitor', 'competitor_strengths',
               existing_type=sa.TEXT(),
               comment='对手优势分析',
               existing_nullable=True)
    op.alter_column('bid_competitor', 'notes',
               existing_type=sa.TEXT(),
               comment='备注',
               existing_nullable=True)
    op.alter_column('bid_competitor', 'created_by',
               existing_type=sa.INTEGER(),
               comment='创建人ID',
               existing_nullable=True)
    op.alter_column('bid_competitor', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bid_competitor', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bid_project_review', 'project_id',
               existing_type=sa.INTEGER(),
               comment='关联投标项目',
               existing_nullable=False)
    op.alter_column('bid_project_review', 'tenant_id',
               existing_type=sa.INTEGER(),
               comment='租户ID',
               existing_nullable=False)
    op.alter_column('bid_project_review', 'result',
               existing_type=sa.VARCHAR(length=20),
               comment='投标结果: won/lost/disqualified/abandoned',
               existing_nullable=False)
    op.alter_column('bid_project_review', 'result_reason',
               existing_type=sa.TEXT(),
               comment='结果原因',
               existing_nullable=True)
    op.alter_column('bid_project_review', 'our_bid_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='我方报价（万元）',
               existing_nullable=True)
    op.alter_column('bid_project_review', 'winning_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='中标价格（万元）',
               existing_nullable=True)
    op.alter_column('bid_project_review', 'official_feedback',
               existing_type=sa.TEXT(),
               comment='采购方评标意见/扣分项',
               existing_nullable=True)
    op.alter_column('bid_project_review', 'personal_summary',
               existing_type=sa.TEXT(),
               comment='业务人员复盘总结',
               existing_nullable=True)
    op.alter_column('bid_project_review', 'lessons_learned',
               existing_type=sa.TEXT(),
               comment='经验教训',
               existing_nullable=True)
    op.alter_column('bid_project_review', 'improvement_actions',
               existing_type=sa.TEXT(),
               comment='改进措施',
               existing_nullable=True)
    op.alter_column('bid_project_review', 'created_by',
               existing_type=sa.INTEGER(),
               comment='创建人ID',
               existing_nullable=True)
    op.alter_column('bid_project_review', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bid_project_review', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sys_dict_item', 'dict_type',
               existing_type=sa.VARCHAR(length=50),
               comment='字典类型(customer_type/tender_type/food_category/delivery_method/...)',
               existing_comment='字典类型(rock_class/section_form/support_type/gas_level/...)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_dict_item', 'dict_type',
               existing_type=sa.VARCHAR(length=50),
               comment='字典类型(rock_class/section_form/support_type/gas_level/...)',
               existing_comment='字典类型(customer_type/tender_type/food_category/delivery_method/...)',
               existing_nullable=False)
    op.alter_column('bid_project_review', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bid_project_review', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bid_project_review', 'created_by',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='创建人ID',
               existing_nullable=True)
    op.alter_column('bid_project_review', 'improvement_actions',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='改进措施',
               existing_nullable=True)
    op.alter_column('bid_project_review', 'lessons_learned',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='经验教训',
               existing_nullable=True)
    op.alter_column('bid_project_review', 'personal_summary',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='业务人员复盘总结',
               existing_nullable=True)
    op.alter_column('bid_project_review', 'official_feedback',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='采购方评标意见/扣分项',
               existing_nullable=True)
    op.alter_column('bid_project_review', 'winning_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='中标价格（万元）',
               existing_nullable=True)
    op.alter_column('bid_project_review', 'our_bid_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='我方报价（万元）',
               existing_nullable=True)
    op.alter_column('bid_project_review', 'result_reason',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='结果原因',
               existing_nullable=True)
    op.alter_column('bid_project_review', 'result',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='投标结果: won/lost/disqualified/abandoned',
               existing_nullable=False)
    op.alter_column('bid_project_review', 'tenant_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='租户ID',
               existing_nullable=False)
    op.alter_column('bid_project_review', 'project_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='关联投标项目',
               existing_nullable=False)
    op.alter_column('bid_competitor', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bid_competitor', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bid_competitor', 'created_by',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='创建人ID',
               existing_nullable=True)
    op.alter_column('bid_competitor', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='备注',
               existing_nullable=True)
    op.alter_column('bid_competitor', 'competitor_strengths',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='对手优势分析',
               existing_nullable=True)
    op.alter_column('bid_competitor', 'competitor_result',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='对手结果: won/lost/disqualified',
               existing_nullable=True)
    op.alter_column('bid_competitor', 'competitor_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='对手报价（万元）',
               existing_nullable=True)
    op.alter_column('bid_competitor', 'competitor_name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='竞争企业名称',
               existing_nullable=False)
    op.alter_column('bid_competitor', 'tenant_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='租户ID',
               existing_nullable=False)
    op.alter_column('bid_chapter', 'source_tags',
               existing_type=sa.TEXT(),
               nullable=True,
               comment=None,
               existing_comment='内容来源标签，逗号分隔: ai_generated,company_db,template,credential',
               existing_server_default=sa.text("''::text"))
    op.alter_column('bid_chapter', 'ai_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               comment=None,
               existing_comment='AI原创占比(0~1)，高风险字段替换后降低',
               existing_server_default=sa.text('0.0'))
    op.alter_column('bid_chapter', 'edit_ratio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='用户编辑占比(0~1)，由反馈飞轮写入',
               existing_nullable=True)
    op.alter_column('audit_log', 'resource',
               existing_type=sa.VARCHAR(length=100),
               comment='操作资源(user/role/mine/drawing/project/...)',
               existing_comment='操作资源(user/role/enterprise/bid_project/credential/...)',
               existing_nullable=False)
    # ### end Alembic commands ###
